<?php
session_start();
require_once 'config.php';
require_once 'components.php';

$role = $_SESSION['user']['role'] ?? ($_SESSION['role'] ?? '');
if (!in_array($role, ['admin', 'teacher'], true)) {
    header('Location: login.php');
    exit;
}

$userId = app_current_user_id();
$teacherId = null;
if ($role === 'teacher') {
    $teacherId = app_teacher_id($pdo, $userId);
    if (!$teacherId) {
        http_response_code(403);
        exit('Teacher record not found.');
    }
}

$sql = 'SELECT gr.id, gr.student_id, gr.generated_by, gr.file_path, gr.created_at,
        s.student_no, s.first_name, s.last_name,
        u.name AS generated_by_name
    FROM grade_reports gr
    JOIN students s ON s.id = gr.student_id
    LEFT JOIN users u ON u.id = gr.generated_by
    WHERE gr.archived_at IS NULL
        AND s.archived_at IS NULL';
$params = [];

if ($role === 'teacher') {
    $sql .= ' AND EXISTS (
        SELECT 1
        FROM enrollments e
        JOIN subjects sub ON sub.id = e.subject_id
        WHERE e.student_id = s.id
            AND e.status = "Enrolled"
            AND e.archived_at IS NULL
            AND sub.archived_at IS NULL
            AND sub.teacher_id = ?
    )
    AND gr.generated_by = ?';
    $params[] = $teacherId;
    $params[] = $userId;
}

$sql .= ' ORDER BY gr.created_at DESC, gr.id DESC';
$stmt = $pdo->prepare($sql);
$stmt->execute($params);
$reports = $stmt->fetchAll();

$pdfCount = 0;
$availablePdfCount = 0;
foreach ($reports as &$report) {
    $resolvedPath = app_resolve_report_path((string) $report['file_path']);
    $isPdf = app_report_is_pdf((string) $report['file_path']);
    $isAvailable = $isPdf && $resolvedPath !== null && is_file($resolvedPath);

    if ($isPdf) {
        $pdfCount++;
    }
    if ($isAvailable) {
        $availablePdfCount++;
    }

    $report['is_pdf'] = $isPdf;
    $report['is_available'] = $isAvailable;
    $report['file_name'] = basename((string) $report['file_path']);
    $report['status_label'] = $isAvailable ? 'Ready' : ($isPdf ? 'Missing File' : 'Legacy Non-PDF');
    $report['status_badge_class'] = $isAvailable
        ? sg_badge_class('success')
        : ($isPdf ? sg_badge_class('warning') : sg_badge_class('inactive'));
}
unset($report);

$customScripts = '<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">';
$customScripts .= "\n<script src=\"https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js\"></script>";
$customScripts .= "\n<script src=\"https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js\"></script>";
$customScripts .= "\n<script>\n$(document).ready(function() {\n    $('#generatedReportsTable').DataTable({ order: [[0, 'desc']] });\n});\n</script>";

$pageTitle = 'Generated Reports | SmartGrade';
require 'header.php';
?>

<?php
$actions = '<a href="generate_report.php" class="btn btn-primary"><i class="bi bi-file-earmark-plus"></i> Generate Report</a>';
sg_page_header('Generated Reports', 'Review saved report files and open available PDF copies.', $actions);
?>

<div class="row row-cols-1 row-cols-md-3 g-4 mb-4">
    <div class="col">
        <div class="card h-100">
            <div class="card-body">
                <p class="text-muted small mb-1">Saved Records</p>
                <h3 class="mb-0"><?= count($reports) ?></h3>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card h-100">
            <div class="card-body">
                <p class="text-muted small mb-1">PDF Records</p>
                <h3 class="mb-0"><?= $pdfCount ?></h3>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card h-100">
            <div class="card-body">
                <p class="text-muted small mb-1">Openable PDFs</p>
                <h3 class="mb-0"><?= $availablePdfCount ?></h3>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <span>Report History</span>
        <span class="text-muted small">Only PDF files can be opened from this page.</span>
    </div>
    <div class="card-body">
        <table id="generatedReportsTable" class="table table-striped table-bordered align-middle">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Generated</th>
                    <th>Student</th>
                    <th>Student No</th>
                    <th>Generated By</th>
                    <th>File</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($reports as $report): ?>
                <tr>
                    <td><?= (int) $report['id'] ?></td>
                    <td><?= htmlspecialchars(date('M d, Y h:i A', strtotime((string) $report['created_at']))) ?></td>
                    <td><?= htmlspecialchars(trim($report['first_name'] . ' ' . $report['last_name'])) ?></td>
                    <td><?= htmlspecialchars((string) $report['student_no']) ?></td>
                    <td><?= htmlspecialchars((string) ($report['generated_by_name'] ?? 'Unknown User')) ?></td>
                    <td><?= htmlspecialchars((string) $report['file_name']) ?></td>
                    <td><span class="<?= htmlspecialchars((string) $report['status_badge_class']) ?>"><?= htmlspecialchars((string) $report['status_label']) ?></span></td>
                    <td>
                        <?php if ($report['is_available']): ?>
                            <a href="open_generated_report.php?id=<?= (int) $report['id'] ?>" class="btn btn-sm btn-primary" target="_blank" rel="noopener noreferrer" data-no-loader>
                                <i class="bi bi-file-earmark-pdf"></i> Open PDF
                            </a>
                        <?php else: ?>
                            <span class="text-muted small">No PDF available</span>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php require 'footer.php'; ?>
